/*
 * Copyright 2016-2021, Cypress Semiconductor Corporation (an Infineon company) or
 * an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 *
 * This software, including source code, documentation and related
 * materials ("Software") is owned by Cypress Semiconductor Corporation
 * or one of its affiliates ("Cypress") and is protected by and subject to
 * worldwide patent protection (United States and foreign),
 * United States copyright laws and international treaty provisions.
 * Therefore, you may use this Software only as provided in the license
 * agreement accompanying the software package from which you
 * obtained this Software ("EULA").
 * If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 * non-transferable license to copy, modify, and compile the Software
 * source code solely for use in connection with Cypress's
 * integrated circuit products.  Any reproduction, modification, translation,
 * compilation, or representation of this Software except as specified
 * above is prohibited without the express written permission of Cypress.
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
 * reserves the right to make changes to the Software without notice. Cypress
 * does not assume any liability arising out of the application or use of the
 * Software or any product or circuit described in the Software. Cypress does
 * not authorize its products for use in any products where a malfunction or
 * failure of the Cypress product may reasonably be expected to result in
 * significant property damage, injury or death ("High Risk Product"). By
 * including Cypress's product in a High Risk Product, the manufacturer
 * of such system or application assumes all risk of such use and in doing
 * so agrees to indemnify Cypress against all liability.
 */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Oct 31 16:42:06 2018. */

#ifndef PB_WICED_HCI_GATT_DB_WICED_HCI_GATT_DB_PB_H_INCLUDED
#define PB_WICED_HCI_GATT_DB_WICED_HCI_GATT_DB_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _wiced_hci_gatt_db_gatt_db_init {
    char dummy_field;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_init) */
} wiced_hci_gatt_db_gatt_db_init;

typedef struct _wiced_hci_gatt_db_gatt_db_characteristic {
    uint32_t handle;
    uint32_t handle_val;
    uint32_t prop;
    uint32_t perm;
    pb_callback_t uuid;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_characteristic) */
} wiced_hci_gatt_db_gatt_db_characteristic;

typedef struct _wiced_hci_gatt_db_gatt_db_descriptor {
    uint32_t handle;
    uint32_t perm;
    pb_callback_t uuid;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_descriptor) */
} wiced_hci_gatt_db_gatt_db_descriptor;

typedef struct _wiced_hci_gatt_db_gatt_db_included_service {
    uint32_t handle;
    pb_callback_t uuid;
    uint32_t svc_handle;
    uint32_t end_grp;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_included_service) */
} wiced_hci_gatt_db_gatt_db_included_service;

typedef struct _wiced_hci_gatt_db_gatt_db_primary_service {
    uint32_t handle;
    pb_callback_t uuid;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_primary_service) */
} wiced_hci_gatt_db_gatt_db_primary_service;

typedef struct _wiced_hci_gatt_db_gatt_db_secondary_service {
    uint32_t handle;
    pb_callback_t uuid;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_secondary_service) */
} wiced_hci_gatt_db_gatt_db_secondary_service;

typedef struct _wiced_hci_gatt_db_gatt_db_set_advert_data {
    pb_callback_t p_data;
    uint32_t size;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_db_set_advert_data) */
} wiced_hci_gatt_db_gatt_db_set_advert_data;

typedef struct _wiced_hci_gatt_db_gatt_start_stop_advert {
    bool start;
/* @@protoc_insertion_point(struct:wiced_hci_gatt_db_gatt_start_stop_advert) */
} wiced_hci_gatt_db_gatt_start_stop_advert;

/* Default values for struct fields */

/* Initializer values for message structs */
#define wiced_hci_gatt_db_gatt_db_primary_service_init_default {0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_secondary_service_init_default {0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_included_service_init_default {0, {{NULL}, NULL}, 0, 0}
#define wiced_hci_gatt_db_gatt_db_characteristic_init_default {0, 0, 0, 0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_descriptor_init_default {0, 0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_set_advert_data_init_default {{{NULL}, NULL}, 0}
#define wiced_hci_gatt_db_gatt_db_init_init_default {0}
#define wiced_hci_gatt_db_gatt_start_stop_advert_init_default {0}
#define wiced_hci_gatt_db_gatt_db_primary_service_init_zero {0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_secondary_service_init_zero {0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_included_service_init_zero {0, {{NULL}, NULL}, 0, 0}
#define wiced_hci_gatt_db_gatt_db_characteristic_init_zero {0, 0, 0, 0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_descriptor_init_zero {0, 0, {{NULL}, NULL}}
#define wiced_hci_gatt_db_gatt_db_set_advert_data_init_zero {{{NULL}, NULL}, 0}
#define wiced_hci_gatt_db_gatt_db_init_init_zero {0}
#define wiced_hci_gatt_db_gatt_start_stop_advert_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define wiced_hci_gatt_db_gatt_db_characteristic_handle_tag 1
#define wiced_hci_gatt_db_gatt_db_characteristic_handle_val_tag 2
#define wiced_hci_gatt_db_gatt_db_characteristic_prop_tag 3
#define wiced_hci_gatt_db_gatt_db_characteristic_perm_tag 4
#define wiced_hci_gatt_db_gatt_db_characteristic_uuid_tag 5
#define wiced_hci_gatt_db_gatt_db_descriptor_handle_tag 1
#define wiced_hci_gatt_db_gatt_db_descriptor_perm_tag 2
#define wiced_hci_gatt_db_gatt_db_descriptor_uuid_tag 3
#define wiced_hci_gatt_db_gatt_db_included_service_handle_tag 1
#define wiced_hci_gatt_db_gatt_db_included_service_uuid_tag 2
#define wiced_hci_gatt_db_gatt_db_included_service_svc_handle_tag 3
#define wiced_hci_gatt_db_gatt_db_included_service_end_grp_tag 4
#define wiced_hci_gatt_db_gatt_db_primary_service_handle_tag 1
#define wiced_hci_gatt_db_gatt_db_primary_service_uuid_tag 2
#define wiced_hci_gatt_db_gatt_db_secondary_service_handle_tag 1
#define wiced_hci_gatt_db_gatt_db_secondary_service_uuid_tag 2
#define wiced_hci_gatt_db_gatt_db_set_advert_data_p_data_tag 1
#define wiced_hci_gatt_db_gatt_db_set_advert_data_size_tag 2
#define wiced_hci_gatt_db_gatt_start_stop_advert_start_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t wiced_hci_gatt_db_gatt_db_primary_service_fields[3];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_secondary_service_fields[3];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_included_service_fields[5];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_characteristic_fields[6];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_descriptor_fields[4];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_set_advert_data_fields[3];
extern const pb_field_t wiced_hci_gatt_db_gatt_db_init_fields[1];
extern const pb_field_t wiced_hci_gatt_db_gatt_start_stop_advert_fields[2];

/* Maximum encoded size of messages (where known) */
/* wiced_hci_gatt_db_gatt_db_primary_service_size depends on runtime parameters */
/* wiced_hci_gatt_db_gatt_db_secondary_service_size depends on runtime parameters */
/* wiced_hci_gatt_db_gatt_db_included_service_size depends on runtime parameters */
/* wiced_hci_gatt_db_gatt_db_characteristic_size depends on runtime parameters */
/* wiced_hci_gatt_db_gatt_db_descriptor_size depends on runtime parameters */
/* wiced_hci_gatt_db_gatt_db_set_advert_data_size depends on runtime parameters */
#define wiced_hci_gatt_db_gatt_db_init_size      0
#define wiced_hci_gatt_db_gatt_start_stop_advert_size 2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WICED_HCI_GATT_DB_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
